version: '3.9'

services:
  postgres:
    image: postgis/postgis:14-3.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local