version: '3.9'

services:
  postgres:
    image: postgis/postgis:14-3.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: [deps, all]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    profiles: [all]
volumes:
  db:
    driver: local