drop table if exists accounts;
create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);
insert into accounts(name,balance)
values('Bob',10000);
insert into accounts(name,balance)
values('Alice',10000);

select * from accounts;

CREATE OR REPLACE PROCEDURE transfer (
    sender int,
    receiver int,
    amount dec
)
language plpgsql
as $$
BEGIN
    UPDATE accounts
    set balance = balance - amount
    where id = sender;

    update accounts
    set balance = balance + amount
    where id = receiver;

    commit;
end; $$; 

call transfer(1,2,1000);